version: '3'

services:

  book-api:
    build:
      context: ./book-api
    ports:
      - 5001:5000
    volumes:
      - ./book-api/src:/app
    

  front-end:
    build:
      context: ./front-end
    ports:
      - 5000:5000
    volumes:
      - ./front-end/src:/app
      